In [1]:
import pandas as pd
import numpy as np

In [2]:
departments_df = pd.read_csv("../data/departments.csv")
doctors_df = pd.read_csv("../data/doctors.csv")
patients_df = pd.read_csv("../data/patients.csv")
admissions_df = pd.read_csv("../data/admissions.csv")
billing_df = pd.read_csv("../data/billing.csv")

In [3]:
patients_df.head()

,patient_id,patient_name,age,gender,city,blood_group,phone,insurance_type
0,PAT00001,Manbir Ramakrishnan,86,Male,Sangli,AB+,918127368619,Self Pay
1,PAT00002,Mason Ramaswamy,87,Male,Mumbai,B+,918086802352,Private Insurance
2,PAT00003,Jeet Bandi,63,Male,Aurangabad,AB+,917899365706,Government Insurance
3,PAT00004,Krishna Ben,2,Female,Satara,B+,918839579154,Self Pay
4,PAT00005,Tamanna Koshy,33,Female,Ahmednagar,O+,917291377641,Corporate Insurance

In [4]:
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      10000 non-null  str
 1   patient_name    10000 non-null  str
 2   age             10000 non-null  int64
 3   gender          10000 non-null  str
 4   city            10000 non-null  str
 5   blood_group     10000 non-null  str
 6   phone           10000 non-null  int64
 7   insurance_type  10000 non-null  str
dtypes: int64(2), str(6)
memory usage: 625.1 KB

In [5]:
print("DEPARTMENTS")
departments_df.info()

print("\nDOCTORS")
doctors_df.info()

print("\nPATIENTS")
patients_df.info()

print("\nADMISSIONS")
admissions_df.info()

print("\nBILLING")
billing_df.info()

DEPARTMENTS
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    10 non-null     str
 1   department_name  10 non-null     str
 2   bed_capacity     10 non-null     int64
dtypes: int64(1), str(2)
memory usage: 372.0 bytes

DOCTORS
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         100 non-null    str
 1   doctor_name       100 non-null    str
 2   department_id     100 non-null    str
 3   specialization    100 non-null    str
 4   experience_years  100 non-null    int64
dtypes: int64(1), str(4)
memory usage: 4.0 KB

PATIENTS
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      10000 non-null  str
 1   patient_name    10000 non-null  str
 2   age             10000 non-null  int64
 3   gender          10000 non-null  str
 4   city            10000 non-null  str
 5   blood_group     10000 non-null  str
 6   phone           10000 non-null  int64
 7   insurance_type  10000 non-null  str
dtypes: int64(2), str(6)
memory usage: 625.1 KB

ADMISSIONS
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   admission_id          15000 non-null  str
 1   patient_id            15000 non-null  str
 2   doctor_id             15000 non-null  str
 3   department_id         15000 non-null  str
 4   admission_date        15000 non-null  str
 5   discharge_date        15000 non-null  str
 6   admission_type        15000 non-null  str
 7   diagnosis             15000 non-null  str
 8   waiting_time_minutes  15000 non-null  int64
 9   emergency_priority    15000 non-null  str
dtypes: int64(1), str(9)
memory usage: 1.1 MB

BILLING
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bill_id            15000 non-null  str
 1   admission_id       15000 non-null  str
 2   treatment_cost     15000 non-null  int64
 3   medicine_cost      15000 non-null  int64
 4   room_charges       15000 non-null  int64
 5   total_bill         15000 non-null  int64
 6   insurance_covered  15000 non-null  float64
 7   payment_status     15000 non-null  str
dtypes: float64(1), int64(4), str(3)
memory usage: 937.6 KB

In [6]:
admissions_df["admission_date"] = pd.to_datetime(
    admissions_df["admission_date"]
)

admissions_df["discharge_date"] = pd.to_datetime(
    admissions_df["discharge_date"]
)

In [7]:
print(admissions_df["admission_date"].dtype)
print(admissions_df["discharge_date"].dtype)

datetime64[us]
datetime64[us]

In [8]:
admissions_df["length_of_stay"] = (
    admissions_df["discharge_date"]
    - admissions_df["admission_date"]
).dt.days

In [9]:
admissions_df["length_of_stay"].describe()

count    15000.000000
mean         7.503467
std          4.012729
min          1.000000
25%          4.000000
50%          7.000000
75%         11.000000
max         14.000000
Name: length_of_stay, dtype: float64

In [10]:
patients_df.describe()

                age         phone
count  10000.000000  1.000000e+04
mean      45.764300  9.180222e+11
std       26.127989  1.157220e+09
min        1.000000  9.160000e+11
25%       23.000000  9.170135e+11
50%       46.000000  9.180405e+11
75%       69.000000  9.190219e+11
max       90.000000  9.199999e+11

In [11]:
patients_df["age"].value_counts().sort_index()

age
1     110
2     133
3      92
4     112
5     121
     ...
86    114
87    117
88    103
89    125
90     99
Name: count, Length: 90, dtype: int64

In [12]:
invalid_age = (
    (patients_df["age"] < 1)
    |
    (patients_df["age"] > 90)
)

print("Invalid ages:", invalid_age.sum())

Invalid ages: 0

In [13]:
patients_df["gender"].value_counts()

gender
Female    5054
Male      4733
Other      213
Name: count, dtype: int64

In [14]:
patients_df["insurance_type"].value_counts()

insurance_type
Private Insurance       4532
Government Insurance    2500
Self Pay                1999
Corporate Insurance      969
Name: count, dtype: int64

In [15]:
patients_df["city"].value_counts()

city
Pune          1055
Thane         1021
Ahmednagar    1018
Mumbai        1014
Satara        1009
Nagpur        1002
Sangli         986
Aurangabad     984
Kolhapur       956
Nashik         955
Name: count, dtype: int64

In [16]:
admissions_df.head()

,admission_id,patient_id,doctor_id,department_id,admission_date,discharge_date,admission_type,diagnosis,waiting_time_minutes,emergency_priority,length_of_stay
0,ADM00001,PAT09407,DOC019,D005,2025-11-05,2025-11-08,Scheduled,Diabetes,86,Not Applicable,3
1,ADM00002,PAT04516,DOC052,D003,2024-11-06,2024-11-15,Emergency,Joint Injury,42,Medium,9
2,ADM00003,PAT06555,DOC001,D004,2025-06-30,2025-07-02,Emergency,Asthma,99,Medium,2
3,ADM00004,PAT00712,DOC041,D004,2024-04-10,2024-04-17,Scheduled,Pneumonia,126,Not Applicable,7
4,ADM00005,PAT06577,DOC046,D009,2025-08-27,2025-08-30,Scheduled,Skin Infection,82,Not Applicable,3

In [17]:
admissions_df["admission_type"].value_counts()

admission_type
Emergency    6024
Scheduled    5282
Referral     2205
Transfer     1489
Name: count, dtype: int64

In [18]:
admissions_df["department_id"].value_counts()

department_id
D005    2126
D008    1862
D001    1788
D007    1668
D002    1559
D003    1457
D010    1428
D006    1245
D004     973
D009     894
Name: count, dtype: int64

In [19]:
admissions_df["diagnosis"].value_counts()

diagnosis
Cancer                     1862
Hypertension               1452
Heart Disease              1137
Viral Infection             854
Pregnancy Complications     839
Gynecological Disorder      829
Appendicitis                725
Fracture                    690
Asthma                      590
Stroke                      550
Diabetes                    529
Arthritis                   523
Kidney Disease              511
Migraine                    506
Neurological Disorder       503
Joint Injury                495
Gastroenteritis             483
Dermatitis                  465
Liver Disease               463
Skin Infection              429
Pneumonia                   318
Trauma                      247
Name: count, dtype: int64

In [20]:
admissions_df["emergency_priority"].value_counts()

emergency_priority
Not Applicable    8976
Medium            2378
High              1821
Critical           924
Low                901
Name: count, dtype: int64

In [21]:
admissions_df["waiting_time_minutes"].describe()

count    15000.000000
mean        95.642333
std         49.480782
min         10.000000
25%         53.000000
50%         96.000000
75%        139.000000
max        180.000000
Name: waiting_time_minutes, dtype: float64

In [22]:
admissions_df["admission_date"].dt.year.value_counts().sort_index()

admission_date
2024    7414
2025    7586
Name: count, dtype: int64

In [24]:
print("Patient statistics:")
print(patients_df[["age"]].describe())

print("\nAdmission statistics:")
print(
    admissions_df[
        ["waiting_time_minutes", "length_of_stay"]
    ].describe()
)

Patient statistics:
                age
count  10000.000000
mean      45.764300
std       26.127989
min        1.000000
25%       23.000000
50%       46.000000
75%       69.000000
max       90.000000

Admission statistics:
       waiting_time_minutes  length_of_stay
count          15000.000000    15000.000000
mean              95.642333        7.503467
std               49.480782        4.012729
min               10.000000        1.000000
25%               53.000000        4.000000
50%               96.000000        7.000000
75%              139.000000       11.000000
max              180.000000       14.000000

In [25]:
billing_df[
    [
        "treatment_cost",
        "medicine_cost",
        "room_charges",
        "total_bill",
        "insurance_covered"
    ]
].describe()

,treatment_cost,medicine_cost,room_charges,total_bill,insurance_covered
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,52310.836000,15501.076067,22502.466467,90314.378533,63161.902749
std,27428.594032,8399.917210,15545.318218,32770.837960,25491.188461
min,5000.000000,1000.000000,1001.000000,11654.000000,7444.370000
25%,28477.000000,8235.750000,9865.750000,65051.750000,43749.802500
50%,52167.500000,15449.000000,19068.000000,90344.000000,61282.855000
75%,76144.750000,22752.250000,32445.750000,114675.250000,80247.102500
max,99995.000000,29998.000000,69874.000000,189979.000000,162816.330000

In [26]:
billing_df["payment_status"].value_counts()

payment_status
Paid              10556
Pending            3001
Partially Paid     1443
Name: count, dtype: int64

In [27]:
admissions_df["diagnosis"].value_counts().head(10)

diagnosis
Cancer                     1862
Hypertension               1452
Heart Disease              1137
Viral Infection             854
Pregnancy Complications     839
Gynecological Disorder      829
Appendicitis                725
Fracture                    690
Asthma                      590
Stroke                      550
Name: count, dtype: int64

In [29]:
department_admissions = department_admissions.reset_index()

department_admissions = department_admissions.merge(
    departments_df[["department_id", "department_name"]],
    on="department_id",
    how="left"
)

department_admissions

,department_id,total_admissions,average_waiting_time,average_length_of_stay,department_name
0,D005,2126,95.944026,7.474130,General Medicine
1,D008,1862,94.926423,7.520408,Oncology
2,D001,1788,96.596756,7.540828,Cardiology
3,D007,1668,95.459832,7.436451,Gynecology
4,D002,1559,94.470173,7.458627,Neurology
5,D003,1457,95.212766,7.621826,Orthopedics
6,D010,1428,95.484594,7.210084,Gastroenterology
7,D006,1245,96.281124,7.661847,Emergency
8,D004,973,96.255910,7.611511,Pediatrics
9,D009,894,96.286353,7.604027,Dermatology

In [30]:
financial_summary = (
    admissions_df[
        ["admission_id", "department_id"]
    ]
    .merge(
        billing_df[
            ["admission_id", "total_bill", "insurance_covered"]
        ],
        on="admission_id",
        how="left"
    )
    .merge(
        departments_df[
            ["department_id", "department_name"]
        ],
        on="department_id",
        how="left"
    )
    .groupby(
        ["department_id", "department_name"]
    )
    .agg(
        total_revenue=("total_bill", "sum"),
        total_insurance_covered=("insurance_covered", "sum"),
        average_bill=("total_bill", "mean")
    )
    .sort_values("total_revenue", ascending=False)
)

financial_summary

,,total_revenue,total_insurance_covered,average_bill
department_id,department_name,,,
D005,General Medicine,190915929,1.338460e+08,89800.531044
D008,Oncology,166753293,1.161163e+08,89556.011278
D001,Cardiology,162137876,1.135197e+08,90681.138702
D007,Gynecology,152881191,1.073112e+08,91655.390288
D002,Neurology,139152395,9.781112e+07,89257.469532
D003,Orthopedics,132913726,9.218432e+07,91224.245710
D010,Gastroenterology,126498009,8.887564e+07,88584.039916
D006,Emergency,113117141,7.881393e+07,90857.141365
D004,Pediatrics,88502138,6.166354e+07,90958.004111
D009,Dermatology,81843980,5.728680e+07,91548.076063

In [28]:
department_admissions = (
    admissions_df
    .groupby("department_id")
    .agg(
        total_admissions=("admission_id", "count"),
        average_waiting_time=("waiting_time_minutes", "mean"),
        average_length_of_stay=("length_of_stay", "mean")
    )
    .sort_values("total_admissions", ascending=False)
)

department_admissions

               total_admissions  average_waiting_time  average_length_of_stay
department_id
D005                       2126             95.944026                7.474130
D008                       1862             94.926423                7.520408
D001                       1788             96.596756                7.540828
D007                       1668             95.459832                7.436451
D002                       1559             94.470173                7.458627
D003                       1457             95.212766                7.621826
D010                       1428             95.484594                7.210084
D006                       1245             96.281124                7.661847
D004                        973             96.255910                7.611511
D009                        894             96.286353                7.604027

In [31]:
hospital_summary = {
    "total_patients": patients_df["patient_id"].nunique(),
    "total_admissions": admissions_df["admission_id"].nunique(),
    "total_bills": billing_df["bill_id"].nunique(),
    "total_revenue": billing_df["total_bill"].sum(),
    "average_waiting_time": admissions_df["waiting_time_minutes"].mean(),
    "average_length_of_stay": admissions_df["length_of_stay"].mean()
}

hospital_summary

{'total_patients': 10000,
 'total_admissions': 15000,
 'total_bills': 15000,
 'total_revenue': np.int64(1354715678),
 'average_waiting_time': np.float64(95.64233333333334),
 'average_length_of_stay': np.float64(7.503466666666666)}

In [32]:
admissions_df.to_csv(
    "../data/admissions_cleaned.csv",
    index=False
)

In [33]:
cleaned_admissions_df = pd.read_csv(
    "../data/admissions_cleaned.csv"
)

print(cleaned_admissions_df.shape)
print(cleaned_admissions_df.columns.tolist())

(15000, 11)
['admission_id', 'patient_id', 'doctor_id', 'department_id', 'admission_date', 'discharge_date', 'admission_type', 'diagnosis', 'waiting_time_minutes', 'emergency_priority', 'length_of_stay']